<a href="https://colab.research.google.com/github/Sanchit-hub/UCS547-Accelerated-Data-Science/blob/main/ASSIGNMENT_1(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab Assignment - 01
UCS-547-Accelerated-Data-Science


In [1]:
import numpy as np

#####Problem: 1
#####Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [2]:
arr=np.array([1,2,3,6,4,5])
reverse=arr[::-1]
print(reverse)

[5 4 6 3 2 1]


#####Problem:2
#####Compare the following numpy arrays:
#####arr1 = np.array([[1, 2], [3, 4]])
#####arr2 = np.array([[1, 2], [3, 4]])

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print((arr1 == arr2))


[[ True  True]
 [ True  True]]


#####Problem:3
#####Find the most frequent value and their indice(s) in the following arrays:
#####i. x = np.array([1,2,3,4,5,1,2,1,1,1])
#####ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

def freq_and_index(a):
    m = int(np.bincount(a).argmax())
    return m, np.where(a == m)[0]

print(freq_and_index(x))
print(freq_and_index(y))

(1, array([0, 5, 7, 8, 9]))
(1, array([0, 1, 2]))


#####Problem:4
#####For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
#####find i. Sum of all elements
#####ii. Sum of all element’s row-wise
#####iii. Sum of all element’s column-wise

In [5]:
gfg = np.matrix('4 1 9; 12 3 1; 4 5 6')
print('sum of all values: ')
print(np.sum(gfg))

print('sum of all rows: ')
print(np.sum(gfg, axis=1))

print('sum of all columns: ')
print(np.sum(gfg, axis=0))

sum of all values: 
45
sum of all rows: 
[[14]
 [16]
 [15]]
sum of all columns: 
[[20  9 16]]
